name: libao
description: A Dart wrapper for the libao library to output audio using a simple API on a wide variety of platforms.
version: 0.1.0
homepage: https://github.com/tiagohm/libao

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  test: ^1.9.2
